application: bb-dubious-test
version: duby
runtime: java
public_root: /public

resource_files:
  - exclude: /build/**

handlers:
  - url: /hello/*
    servlet: controllers.HelloController
    name: hello